### ISSUE TITLE
IncompatibleClassChangeError

### ISSUE THREAD

**Issue by h6ah4i** [h6ah4i/android-openslmediaplayer#8]
Device: Galaxy S2 (SC-02C)
OS: Android 4.0.3
Affected version:  develop branch (17ade5213d407945c9f22ff18bdbd1a679f24ead)

```
E/AndroidRuntime( 4245): FATAL EXCEPTION: main
E/AndroidRuntime( 4245): java.lang.IncompatibleClassChangeError: interface not implemented
E/AndroidRuntime( 4245): 	at com.h6ah4i.android.media.opensl.OpenSLMediaPlayer.closeQuietly(OpenSLMediaPlayer.java:750)
E/AndroidRuntime( 4245): 	at com.h6ah4i.android.media.opensl.OpenSLMediaPlayer.releaseOpenedContentFileDescriptor(OpenSLMediaPlayer.java:630)
E/AndroidRuntime( 4245): 	at com.h6ah4i.android.media.opensl.OpenSLMediaPlayer.release(OpenSLMediaPlayer.java:319)
E/AndroidRuntime( 4245): 	at com.h6ah4i.android.example.openslmediaplayer.app.model.GlobalAppController.playerRelease(GlobalAppController.java:837)
E/AndroidRuntime( 4245): 	at com.h6ah4i.android.example.openslmediaplayer.app.model.GlobalAppController.releaseAllPlayerResources(GlobalAppController.java:1696)
E/AndroidRuntime( 4245): 	at com.h6ah4i.android.example.openslmediaplayer.app.model.GlobalAppController.setPlayerImplType(GlobalAppController.java:1449)
E/AndroidRuntime( 4245): 	at com.h6ah4i.android.example.openslmediaplayer.app.model.GlobalAppController.onReceiveNavigationDrawerEvent(GlobalAppController.java:556)
E/AndroidRuntime( 4245): 	at com.h6ah4i.android.example.openslmediaplayer.app.model.GlobalAppController.onReceiveAppEvent(GlobalAppController.java:514)
E/AndroidRuntime( 4245): 	at com.h6ah4i.android.example.openslmediaplayer.app.model.GlobalAppController$AppEventReceiver.onReceiveAppEvent(GlobalAppController.java:128)
E/AndroidRuntime( 4245): 	at com.h6ah4i.android.example.openslmediaplayer.app.model.GlobalAppController$AppEventReceiver.onReceiveAppEvent(GlobalAppController.java:106)
E/AndroidRuntime( 4245): 	at com.h6ah4i.android.example.openslmediaplayer.app.framework.AppEventBus$Receiver.onReceive(AppEventBus.java:50)
E/AndroidRuntime( 4245): 	at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
E/AndroidRuntime( 4245): 	at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
E/AndroidRuntime( 4245): 	at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
E/AndroidRuntime( 4245): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 4245): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 4245): 	at android.app.ActivityThread.main(ActivityThread.java:4507)
E/AndroidRuntime( 4245): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4245): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 4245): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:980)
E/AndroidRuntime( 4245): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)
E/AndroidRuntime( 4245): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by h6ah4i** [comment]
Cause: the `AssetFileDescriptor` class doesn't implement `Closeable` on older than API level 19.  
http://developer.android.com/reference/android/content/res/AssetFileDescriptor.html
